# Generated by Django 4.1.1 on 2023-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('date', models.DateField()),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
    ]
