# Generated by Django 4.1.1 on 2023-05-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_specialevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialevent',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
